language: node_js
node_js:
  - "7.10"

branches:
  only:
    - master

before_script:
  - npm install enhanced-resolve@3.3.0
  - npm install -g @angular/cli

script: 
  - ng build --prod


notifications:
  email:
    on_failure: change
    on_success: change