language: node_js
node_js:
  - "7.10"

branches:
  only:
    - master

before_script:
  - npm install enhanced-resolve@3.3.0
  - npm install -g @angular/cli

script: 
  - ng build --prod


notifications:
  email:
    on_failure: change
    on_success: change


deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "dbyassmith-deploy-test"
  skip_cleanup: true
  local_dir: dist